flaskr/blueprints/bp_asistencias.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
import datetime

from ..scripts.personal import Bombero
from ..scripts.eventos import Evento
from ..scripts.unidades import Unidad
from ..scripts.asistencias import Asistencia_Cabecera, Asistencia_Detalle, Add_Cabecera, Verificar_Conducta_Mes

from .bp_index import Admin_Required, User_Required

bp = Blueprint('asistencias', __name__)

@bp.route('/cargar/', methods=['GET'])
@User_Required
def Index():
    return render_template('asistencias/cargar_planilla.html', eventos=Evento.Get_Eventos())

@bp.route('/cargar/<evento_nombre>', methods=['POST'])
@User_Required
def Nueva_Planilla(evento_nombre):
    if evento_nombre != 'Conducta':
        evento = Evento.Get_Evento_By_Nombre(evento_nombre)
        id_cabecera = Add_Cabecera(evento.id)
        
        flash('Planilla de asistencias cargada correctamente.')
        return render_template('asistencias/cargar_planilla_detalle.html', cabecera=Asistencia_Cabecera.Get_By_ID(id_cabecera), evento=evento, bomberos=Bombero.Get_Bomberos(), unidades=Unidad.Get_Unidades())
    
    elif Verificar_Conducta_Mes():
        flash('Ya se ha cargado la planilla de conducta para este mes.')
        return redirect(url_for('asistencias.Index'))
    
    else:
        evento = Evento.Get_Evento_By_Nombre(evento_nombre)
        id_cabecera = Add_Cabecera(evento.id)
        
        flash('Planilla de conducta cargada correctamente.')
        return render_template('asistencias/cargar_conducta.html', cabecera=Asistencia_Cabecera.Get_By_ID(id_cabecera), evento=evento, bomberos=Bombero.Get_Bomberos())

@bp.route('/cargar/detalles', methods=['POST'])
@User_Required
def Cargar_Detalles():
    id_cabecera = int(request.form['id_cabecera'])
    cabecera = Asistencia_Cabecera.Get_By_ID(id_cabecera)

    descripcion = request.form.get('descripcion')
    cabecera.descripcion = descripcion
    
    for bombero in Bombero.Get_Bomberos():
        estado = int(request.form[f'{bombero.legajo}_estado'])
        id_unidad = request.form.get(f'{bombero.legajo}_unidad')
        try:
            id_unidad = int(id_unidad)
        except (TypeError, ValueError):
            id_unidad = None
        
        detalle = Asistencia_Detalle(None, cabecera.id, bombero.legajo, id_unidad, estado)
        detalle.Add()
        cabecera.Add_Detalle(detalle)
        cabecera.Set()
    
    flash('Detalles de asistencias cargados correctamente.')
    return redirect(url_for('asistencias.Index'))

@bp.route('/verificar/', methods=['GET'])
@Admin_Required
def Verificar_Planillas():
    return render_template('asistencias/verificar_planillas.html', planillas=Asistencia_Cabecera.Get_Pendientes(), Evento=Evento, Bombero=Bombero, Unidad=Unidad)

@bp.route('/verificar/si/<int:id>', methods=['POST'])
@Admin_Required
def Aceptar_Planilla(id):
    cabecera = Asistencia_Cabecera.Get_By_ID(id)
    cabecera.fecha_aceptada = datetime.datetime.now().strftime('%Y-%m-%d')
    cabecera.legajo_responsable = session['user']['legajo']
    cabecera.Set()
    
    flash('Planilla aceptada correctamente.')
    return redirect(url_for('asistencias.Verificar_Planillas'))

@bp.route('/verificar/no/<int:id>', methods=['POST'])
@Admin_Required
def Rechazar_Planilla(id):
    cabecera = Asistencia_Cabecera.Get_By_ID(id)
    cabecera.Del()
    
    flash('Planilla rechazada y eliminada correctamente.')
    return redirect(url_for('asistencias.Verificar_Planillas'))

@bp.route('/ver/', methods=['GET'])
def Ver_Planillas():
    return render_template('asistencias/ver_planillas.html', planillas=Asistencia_Cabecera.Get_Aceptadas(), Evento=Evento, Bombero=Bombero, Unidad=Unidad)

@bp.route('/ver', methods=['GET'])
def Ver_Planillas_Fecha():
    fecha_inicio = request.args.get('fecha_inicio')
    fecha_fin = request.args.get('fecha_fin')
    
    if not fecha_inicio:
        fecha_inicio = datetime.datetime.now().strftime('%Y-%m-%d')
    
    if not fecha_fin:
        fecha_fin = fecha_inicio
    
    return render_template(
        'asistencias/ver_planillas.html',
        planillas=Asistencia_Cabecera.Get_Aceptadas_Rango(fecha_inicio, fecha_fin),
        Evento=Evento,Bombero=Bombero, Unidad=Unidad,
        fecha_inicio=fecha_inicio,
        fecha_fin=fecha_fin
    )

flaskr/templates/asistencias/cargar_conducta.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='asistencias.css') }}">
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

{% block center %}
    <form action="{{ url_for('asistencias.Cargar_Detalles') }}" method="post">
        <table>
            <col width="75%"><col width="25%">
            <thead>
                <tr>
                    <th>
                        Planilla #{{ cabecera.id }}
                        <input type="hidden" name="id_cabecera" value="{{ cabecera.id }}">
                    </th>
                    <th>
                        {{ evento.nombre }}, {{ cabecera.fecha_creada }}
                    </th>
                </tr>
                <tr>
                    <th>Bombero</th>
                    <th>Conducta</th>
                </tr>
            </thead>
            <tbody>
                {% for bombero in bomberos %}
                    <tr>
                        <td>{{ bombero.apellido_nombre }}</td>
                        <td class="radio">
                            <input type="radio" id="{{bombero.legajo}}_presente" name="{{bombero.legajo}}_estado" value="1" required>
                            <label for="{{bombero.legajo}}_presente">Suficiente</label>

                            <input type="radio" id="{{bombero.legajo}}_ausente" name="{{bombero.legajo}}_estado" value="0" required>
                            <label for="{{bombero.legajo}}_ausente">Deficiente</label>
                        </td>
                    </tr>
                {% endfor %}

                <tr>
                    <th colspan="2">
                        <input type="submit" value="Cargar">
                    </th>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

flaskr/templates/asistencias/cargar_planilla.html
{% if session['user']['permisos'] > 1 %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'base_user.html' %}
{% endif %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='asistencias.css') }}">
{% endblock %}

{% block center %}
    <fieldset>
        <legend>Cargar</legend>
        <form method="post">
            {% for evento in eventos %}
                {% if session['user']['permisos'] > 1 %}
                    <button type="submit" name="evento" formaction="{{ url_for('asistencias.Nueva_Planilla', evento_nombre=evento.nombre) }}">
                        <span>{{ evento.nombre }}</span>
                    </button>
                {% else %}
                    {% if evento.nombre != 'Conducta' %}
                        <button type="submit" name="evento" formaction="{{ url_for('asistencias.Nueva_Planilla', evento_nombre=evento.nombre) }}">
                            <span>{{ evento.nombre }}</span>
                        </button>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </form>
    </fieldset>
{% endblock %}

flaskr/templates/asistencias/cargar_planilla_detalle.html
{% if session['user']['permisos'] > 1 %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'base_user.html' %}
{% endif %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='asistencias.css') }}">
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

{% block center %}
    <form action="{{ url_for('asistencias.Cargar_Detalles') }}" method="post">
        <table>
            <col width="50%"><col width="25%"><col width="25%">
            <thead>
                <tr>
                    <th>
                        Planilla #{{ cabecera.id }}
                        <input type="hidden" name="id_cabecera" value="{{ cabecera.id }}">
                    </th>
                    <th>
                        Evento: {{ evento.nombre }}
                        <input type="hidden" name="descripcion">
                    </th>
                    <th>
                        {{ cabecera.fecha_creada }}
                    </th>
                </tr>
                <tr>
                    <th>Bombero</th>
                    <th>Estado</th>
                    <th>Unidad</th>
                </tr>
            </thead>
            <tbody>
                {% for bombero in bomberos %}
                    <tr>
                        <td>{{ bombero.apellido_nombre }}</td>
                        <td class="radio">
                            <input type="radio" id="{{bombero.legajo}}_presente" name="{{bombero.legajo}}_estado" value="1" required>
                            <label for="{{bombero.legajo}}_presente">Presente</label>

                            <input type="radio" id="{{bombero.legajo}}_licencia" name="{{bombero.legajo}}_estado" value="2" required>
                            <label for="{{bombero.legajo}}_licencia">Licencia</label>

                            <input type="radio" id="{{bombero.legajo}}_ausente" name="{{bombero.legajo}}_estado" value="0" required>
                            <label for="{{bombero.legajo}}_ausente">Ausente</label>
                        </td>
                        <td>
                            <select name="{{bombero.legajo}}_unidad" style="width: 100%;">
                                <option value="{{ None }}" selected></option>
                                {% for unidad in unidades %}
                                    <option value="{{ unidad.id }}">{{ unidad.nombre }} ({{ unidad.patente }})</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                {% endfor %}

                <tr>
                    <th colspan="3">
                        <input type="submit" value="Cargar">
                    </th>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

{% block right %}
    <fieldset>
        <legend>Descripción</legend>
        <textarea name="descripcion_textarea" rows="10" oninput="actualizar_Descripcion()"></textarea>
    </fieldset>
{% endblock %}

flaskr/templates/asistencias/ver_planillas.html
{% if session['user']['permisos'] > 1 %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'base_user.html' %}
{% endif %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='asistencias.css') }}">
{% endblock %}

{% block center %}
    {% for planilla in planillas %}
        <form action="" method="post">
            <table style="margin-bottom: 1rem;">
                <col width="50%"><col width="25%"><col width="25%">
                <thead>
                    <tr>
                        <th>
                            <div>
                                <span>
                                    Planilla #{{ planilla.id }}
                                </span>
                                <span>
                                    Evento: {{ Evento.Get_Evento_By_ID(planilla.id_evento).nombre }}
                                </span>
                            </div>
                        </th>
                        <th colspan="2">
                            <div>
                                <span>
                                    Creada: {{ planilla.fecha_creada }}
                                </span>
                                <span>
                                    Aceptada: {{ planilla.fecha_aceptada }}
                                </span>
                            </div>
                        </th>
                    </tr>
                    <tr>
                        <th colspan="3">
                            Descripción: 
                            {% if planilla.descripcion != None %}
                                {{ planilla.descripcion }}
                            {% else %}
                                No tiene
                            {% endif %}
                        </th>
                    </tr>
                    <tr>
                        <th>
                            Bombero (Legajo)
                        </th>
                        <th>
                            Unidad
                        </th>
                        <th>
                            Asistencia
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for detalle in planilla.detalles %}
                        <tr>
                            <td>
                                {{ Bombero.Get_Bombero_By_Legajo(detalle.legajo).apellido_nombre }} ({{ detalle.legajo }})
                            </td>
                            <td>
                                {% if detalle.id_unidad != None %}
                                    {{ Unidad.Get_Unidad_By_ID(detalle.id_unidad).nombre }} ({{Unidad.Get_Unidad_By_ID(detalle.id_unidad).patente}})
                                {% endif %}
                            </td>
                            <td style="text-align: center;">
                                {% if detalle.estado == 1 %}
                                    ✔
                                {% elif detalle.estado == 2 %}
                                    Lic.
                                {% else %}
                                    ✘
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    {% endfor %}
{% endblock %}

{% block right %}
    <form action="{{ url_for('asistencias.Ver_Planillas_Fecha') }}" method="get">
        <fieldset>
            <legend>Desde-Hasta</legend>

            <div>
                <input type="date" name="fecha_inicio" value="{{ fecha_inicio or '' }}">
                <input type="date" name="fecha_fin" value="{{ fecha_fin or '' }}">
            </div>

            <button type="submit">
                <span>Filtrar</span>
            </button>
        </fieldset>
    </form>
{% endblock %}

flaskr/templates/asistencias/verificar_planillas.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='asistencias.css') }}">
{% endblock %}

{% block center %}
    {% for planilla in planillas %}
        <form action="" method="post">
            <table style="margin-bottom: 1rem;">
                <col width="50%"><col width="25%"><col width="25%">
                <thead>
                    <tr>
                        <th>
                            Planilla #{{ planilla.id }}
                        </th>
                        <th>
                            {% set evento = Evento.Get_Evento_By_ID(planilla.id_evento) %}
                            Evento: {{ evento.nombre }}
                        </th>
                        <th>
                            {{ planilla.fecha_creada }}
                        </th>
                    </tr>
                    <tr>
                        <th colspan="3">
                            Descripción: 
                            {% if planilla.descripcion != None %}
                                {{ planilla.descripcion }}
                            {% else %}
                                No tiene
                            {% endif %}
                        </th>
                    </tr>
                    <tr>
                        <th>
                            Bombero (Legajo)
                        </th>
                        <th>
                            Unidad
                        </th>
                        <th>
                            {% if evento.nombre != 'Conducta' %}
                                Asistencia
                            {% else %}
                                Conducta
                            {% endif %}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for detalle in planilla.detalles %}
                        <tr>
                            <td>
                                {{ Bombero.Get_Bombero_By_Legajo(detalle.legajo).apellido_nombre }} ({{ detalle.legajo }})
                            </td>
                            <td>
                                {% if detalle.id_unidad != None %}
                                    {{ Unidad.Get_Unidad_By_ID(detalle.id_unidad).nombre }} ({{Unidad.Get_Unidad_By_ID(detalle.id_unidad).patente}})
                                {% endif %}
                            </td>
                            <td>
                                {% if evento.nombre != 'Conducta' %}
                                    {% if detalle.estado == 1 %}
                                        Asistió
                                    {% elif detalle.estado == 2 %}
                                        Licencia
                                    {% else %}
                                        Ausente
                                    {% endif %}
                                {% else %}
                                    {% if detalle.estado == 1 %}
                                        Suficiente
                                    {% else %}
                                        Deficiente
                                    {% endif %}
                                {% endif %}

                            </td>
                        </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="3">
                            <div class="botones">
                                <button type="submit" formaction="{{ url_for('asistencias.Aceptar_Planilla', id=planilla.id) }}">
                                    <span>Aceptar</span>
                                </button>
    
                                <button type="submit" formaction="{{ url_for('asistencias.Rechazar_Planilla', id=planilla.id) }}">
                                    <span>Rechazar</span>
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    {% endfor %}
{% endblock %}