flaskr/blueprints/bp_eventos.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from ..scripts.eventos import Evento
from .bp_index import Admin_Required

bp = Blueprint('eventos', __name__)

@bp.route('/', methods=['GET'])
@Admin_Required
def Eventos():
    return render_template('datos/eventos.html', eventos=Evento.Get_Eventos())

@bp.route('/subir', methods=['POST'])
@Admin_Required
def Subir():
    id = request.form['id']
    nombre = request.form['nombre']
    puntos = request.form['puntos']

    evento = Evento(
        id=id,
        nombre=nombre,
        puntos=puntos
    )

    if evento.id == '' or Evento.Get_Evento_By_ID(evento.id) is None:
        evento.Add()

    else:
        evento.Set()

    flash('Evento agregado/actualizado exitosamente.')
    return redirect(url_for('eventos.Eventos'))

flaskr/blueprints/bp_personal.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from ..scripts.personal import Bombero
from .bp_index import Admin_Required

bp = Blueprint('personal', __name__)

@bp.route('/', methods=['GET'])
@Admin_Required
def Personal():
    return render_template('datos/personal.html', personal=Bombero.Get_Bomberos())

@bp.route('/subir', methods=['POST'])
@Admin_Required
def Subir():
    legajo = request.form['legajo']
    dni = request.form['dni']
    username = request.form['username']
    password = request.form['password']
    apellido_nombre = request.form['apellido_nombre']
    telefono = request.form['telefono']
    fecha_nacimiento = request.form['fecha_nacimiento']
    provincia = request.form['provincia']
    lugar = request.form['lugar']
    permisos = request.form['permisos']

    bombero = Bombero(
        legajo=legajo,
        dni=dni,
        username=username,
        password=password,
        apellido_nombre=apellido_nombre,
        telefono=telefono,
        fecha_nacimiento=fecha_nacimiento,
        provincia=provincia,
        lugar=lugar,
        permisos=permisos
    )

    if Bombero.Get_Bombero_By_Legajo(legajo) is None:
        bombero.Add()

    else:
        bombero.Set()

    flash('Bombero agregado/actualizado exitosamente.')
    return redirect(url_for('personal.Personal'))

flaskr/blueprints/bp_unidades.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from ..scripts.unidades import Unidad
from .bp_index import Admin_Required

bp = Blueprint('unidades', __name__)

@bp.route('/', methods=['GET'])
@Admin_Required
def Unidades():
    return render_template('datos/unidades.html', unidades=Unidad.Get_Unidades())

@bp.route('/subir', methods=['POST'])
@Admin_Required
def Subir():
    id = request.form['id']
    nombre = request.form['nombre']
    patente = request.form['patente']
    estado = request.form['estado']

    unidad = Unidad(
        id=id,
        nombre=nombre,
        patente=patente,
        estado=estado if estado else 1
    )

    if unidad.id == '' or Unidad.Get_Unidad_By_ID(unidad.id) is None:
        unidad.Add()

    else:
        unidad.Set()

    flash('Unidad agregada/actualizada exitosamente.')
    return redirect(url_for('unidades.Unidades'))

flaskr/templates/datos/eventos.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='datos.css') }}">
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

{% block center %}
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Puntos</th>
            </tr>
        </thead>

        <tbody>
            {% for Evento in eventos %}
                <tr onclick="tr_Seleccionar(this)">
                    <td>{{ Evento.id }}</td>
                    <td>{{ Evento.nombre }}</td>
                    <td>{{ Evento.puntos }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block right %}
    <form id="abm" action="{{ url_for('eventos.Subir') }}" method="post">
        <fieldset>
            <legend>ID (no modificable)</legend>
            <input type="text" name="id" value="" readonly>
        </fieldset>
        
        <fieldset>
            <legend>Nombre</legend>
            <input type="text" name="nombre" value="">
        </fieldset>

        <fieldset>
            <legend>Puntos</legend>
            <input type="number" name="puntos" min="0.0" max="10.0" step="0.1">
        </fieldset>

        <fieldset>
            <legend>Acciones</legend>
            <button onclick="form_Limpiar()">
                <span>Limpiar</span>
            </button>
            <button type="submit">
                <span>Guardar</span>
            </button>
        </fieldset>
    </form>
{% endblock %}

flaskr/templates/datos/personal.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='datos.css') }}">
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

{% block center %}
    <table>
        <col width="15%"><col width="10%"><col width="10%"><col width="10%"><col width="10%"><col width="10%"><col width="10%"><col width="10%"><col width="10%">
        <thead>
            <tr>
                <th>Legajo</th>
                <th>DNI</th>
                <th>Usuario</th>
                <th>Contraseña</th>
                <th>Apellido, Nombre</th>
                <th>Teléfono</th>
                <th>Nacimiento</th>
                <th>Provincia</th>
                <th>Lugar</th>
                <th style="display: none;">Permisos</th>
            </tr>
        </thead>

        <tbody>
            {% for Bombero in personal %}
                <tr onclick="tr_Seleccionar(this)">
                    <td>{{ Bombero.legajo }}</td>
                    <td>{{ Bombero.dni }}</td>
                    <td>{{ Bombero.username }}</td>
                    <td>{{ Bombero.password }}</td>
                    <td>{{ Bombero.apellido_nombre }}</td>
                    <td>{{ Bombero.telefono }}</td>
                    <td>{{ Bombero.fecha_nacimiento }}</td>
                    <td>{{ Bombero.provincia }}</td>
                    <td>{{ Bombero.lugar }}</td>
                    <td style="display: none;">{{ Bombero.permisos }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block right %}
    <form id="abm" action="{{ url_for('personal.Subir') }}" method="post">
        <fieldset>
            <legend>Legajo</legend>
            <input type="text" name="legajo" value="" required>
        </fieldset>

        <fieldset>
            <legend>DNI</legend>
            <input type="text" name="dni" value="" required>
        </fieldset>

        <fieldset>
            <legend>Usuario</legend>
            <input type="text" name="username" value="" required>
        </fieldset>

        <fieldset>
            <legend>Contraseña</legend>
            <input type="text" name="password" value="" required>
        </fieldset>

        <fieldset>
            <legend>Apellido, Nombre</legend>
            <input type="text" name="apellido_nombre" value="" required>
        </fieldset>

        <fieldset>
            <legend>Teléfono</legend>
            <input type="tel" pattern="\d{2,4}[ -]?\d{6}" name="telefono" value="" title="Formato: 1234 567891 o 1234-567891" required>
        </fieldset>

        <fieldset>
            <legend>Nacimiento</legend>
            <input type="date" name="fecha_nacimiento" value="" required>
        </fieldset>

        <fieldset>
            <legend>Provincia</legend>
            <input type="text" name="provincia" value="" required>
        </fieldset>

        <fieldset>
            <legend>Lugar</legend>
            <input type="text" name="lugar" value="" required>
        </fieldset>

        <fieldset>
            <legend>Permisos</legend>
            <select name="permisos" required>
                <option hidden disabled selected value></option>
                <option value="0">Baja</option>
                <option value="1">Usuario</option>
                <option value="2">Admin</option>
            </select>
        </fieldset>

        <fieldset>
            <legend>Acciones</legend>
            <button onclick="form_Limpiar()">
                <span>Limpiar</span>
            </button>
            <button type="submit">
                <span>Guardar</span>
            </button>
        </fieldset>
    </form>
{% endblock %}

flaskr/templates/datos/unidades.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='datos.css') }}">
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

{% block center %}
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Patente</th>
                <th style="display: none;">Estado</th>
            </tr>
        </thead>

        <tbody>
            {% for Unidad in unidades %}
                <tr onclick="tr_Seleccionar(this)">
                    <td>{{ Unidad.id }}</td>
                    <td>{{ Unidad.nombre }}</td>
                    <td>{{ Unidad.patente }}</td>
                    <td style="display: none;">{{ Unidad.estado }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block right %}
    <form id="abm" action="{{ url_for('unidades.Subir') }}" method="post">
        <fieldset>
            <legend>ID (no modificable)</legend>
            <input type="text" name="id" value="" readonly>
        </fieldset>
        
        <fieldset>
            <legend>Nombre</legend>
            <input type="text" name="nombre" value="" required>
        </fieldset>
        
        <fieldset>
            <legend>Patente</legend>
            <input type="text" name="patente" value="" required>
        </fieldset>

        <fieldset>
            <legend>Estado</legend>
            <select name="permisos" required>
                <option hidden disabled selected value></option>
                <option value="0">Inactiva</option>
                <option value="1">Activa</option>
            </select>
        </fieldset>

        <fieldset>
            <legend>Acciones</legend>
            <button onclick="form_Limpiar()">
                <span>Limpiar</span>
            </button>
            <button type="submit">
                <span>Guardar</span>
            </button>
        </fieldset>
    </form>
{% endblock %}