flaskr/blueprints/bp_asistencias.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
import datetime

from ..scripts.personal import Bombero
from ..scripts.eventos import Evento
from ..scripts.unidades import Unidad
from ..scripts.asistencias import Asistencia_Cabecera, Asistencia_Detalle, Add_Cabecera, Verificar_Conducta_Mes

from .bp_index import Admin_Required, User_Required

bp = Blueprint('asistencias', __name__)

@bp.route('/cargar/', methods=['GET'])
@User_Required
def Index():
    return render_template('asistencias/cargar_planilla.html', eventos=Evento.Get_Eventos())

@bp.route('/cargar/<evento_nombre>', methods=['POST'])
@User_Required
def Nueva_Planilla(evento_nombre):
    if evento_nombre != 'Conducta':
        evento = Evento.Get_Evento_By_Nombre(evento_nombre)
        id_cabecera = Add_Cabecera(evento.id)
        
        flash('Planilla de asistencias cargada correctamente.')
        return render_template('asistencias/cargar_planilla_detalle.html', cabecera=Asistencia_Cabecera.Get_By_ID(id_cabecera), evento=evento, bomberos=Bombero.Get_Bomberos(), unidades=Unidad.Get_Unidades())
    
    elif Verificar_Conducta_Mes():
        flash('Ya se ha cargado la planilla de conducta para este mes.')
        return redirect(url_for('asistencias.Index'))
    
    else:
        evento = Evento.Get_Evento_By_Nombre(evento_nombre)
        id_cabecera = Add_Cabecera(evento.id)
        
        flash('Planilla de conducta cargada correctamente.')
        return render_template('asistencias/cargar_conducta.html', cabecera=Asistencia_Cabecera.Get_By_ID(id_cabecera), evento=evento, bomberos=Bombero.Get_Bomberos())

@bp.route('/cargar/detalles', methods=['POST'])
@User_Required
def Cargar_Detalles():
    id_cabecera = int(request.form['id_cabecera'])
    cabecera = Asistencia_Cabecera.Get_By_ID(id_cabecera)

    descripcion = request.form.get('descripcion')
    cabecera.descripcion = descripcion
    
    for bombero in Bombero.Get_Bomberos():
        estado = int(request.form[f'{bombero.legajo}_estado'])
        id_unidad = request.form.get(f'{bombero.legajo}_unidad')
        try:
            id_unidad = int(id_unidad)
        except (TypeError, ValueError):
            id_unidad = None
        
        detalle = Asistencia_Detalle(None, cabecera.id, bombero.legajo, id_unidad, estado)
        detalle.Add()
        cabecera.Add_Detalle(detalle)
        cabecera.Set()
    
    flash('Detalles de asistencias cargados correctamente.')
    return redirect(url_for('asistencias.Index'))

@bp.route('/verificar/', methods=['GET'])
@Admin_Required
def Verificar_Planillas():
    return render_template('asistencias/verificar_planillas.html', planillas=Asistencia_Cabecera.Get_Pendientes(), Evento=Evento, Bombero=Bombero, Unidad=Unidad)

@bp.route('/verificar/si/<int:id>', methods=['POST'])
@Admin_Required
def Aceptar_Planilla(id):
    cabecera = Asistencia_Cabecera.Get_By_ID(id)
    cabecera.fecha_aceptada = datetime.datetime.now().strftime('%Y-%m-%d')
    cabecera.legajo_responsable = session['user']['legajo']
    cabecera.Set()
    
    flash('Planilla aceptada correctamente.')
    return redirect(url_for('asistencias.Verificar_Planillas'))

@bp.route('/verificar/no/<int:id>', methods=['POST'])
@Admin_Required
def Rechazar_Planilla(id):
    cabecera = Asistencia_Cabecera.Get_By_ID(id)
    cabecera.Del()
    
    flash('Planilla rechazada y eliminada correctamente.')
    return redirect(url_for('asistencias.Verificar_Planillas'))

@bp.route('/ver/', methods=['GET'])
def Ver_Planillas():
    return render_template('asistencias/ver_planillas.html', planillas=Asistencia_Cabecera.Get_Aceptadas(), Evento=Evento, Bombero=Bombero, Unidad=Unidad)

@bp.route('/ver', methods=['GET'])
def Ver_Planillas_Fecha():
    fecha_inicio = request.args.get('fecha_inicio')
    fecha_fin = request.args.get('fecha_fin')
    
    if not fecha_inicio:
        fecha_inicio = datetime.datetime.now().strftime('%Y-%m-%d')
    
    if not fecha_fin:
        fecha_fin = fecha_inicio
    
    return render_template(
        'asistencias/ver_planillas.html',
        planillas=Asistencia_Cabecera.Get_Aceptadas_Rango(fecha_inicio, fecha_fin),
        Evento=Evento,Bombero=Bombero, Unidad=Unidad,
        fecha_inicio=fecha_inicio,
        fecha_fin=fecha_fin
    )

flaskr/blueprints/bp_calificaciones.py
import datetime
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from ..scripts.calificaciones import Calificacion
from ..scripts.personal import Bombero
from ..scripts.eventos import Evento

bp = Blueprint('calificaciones', __name__)

@bp.route('/mensual', methods=['GET'])
def Mensual():
    return render_template('calificaciones/mensual.html', calificaciones=Calificacion.Get_Mensual(), Calificacion=Calificacion, Bombero=Bombero, Evento=Evento)

@bp.route('/semestral', methods=['GET'])
def Semestral():
    return render_template('calificaciones/semestral.html', calificaciones=Calificacion.Get_Semestral(), Calificacion=Calificacion, Bombero=Bombero, Evento=Evento)

@bp.route('/anual', methods=['GET'])
def Anual():
    return render_template('calificaciones/anual.html', calificaciones=Calificacion.Get_Anual(), Calificacion=Calificacion, Bombero=Bombero, Evento=Evento)

@bp.route('/historico', methods=['GET'])
def Historico():
    fecha_inicio = request.args.get('fecha_inicio')
    fecha_fin = request.args.get('fecha_fin')
    
    return render_template(
        'calificaciones/historico.html',
        calificaciones=Calificacion.Get_Historico(fecha_inicio, fecha_fin),
        Calificacion=Calificacion, Bombero=Bombero, Evento=Evento,
        fecha_inicio=fecha_inicio, fecha_fin=fecha_fin
    )

flaskr/blueprints/bp_index.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from functools import wraps
from ..scripts.personal import Bombero

def Admin_Required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            flash('Inicie sesión para acceder a esta página.')
            return redirect(url_for('index.Index'))
        
        elif session['user']['permisos'] < 2:
            flash('No tiene permisos de administrador para acceder a esta página.')
            return redirect(url_for('index.Index'))
        
        return f(*args, **kwargs)
    
    return decorated_function

def User_Required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            flash('Inicie sesión para acceder a esta página.')
            return redirect(url_for('index.Index'))
        
        elif session['user']['permisos'] < 1:
            flash('No tiene permisos de usuario para acceder a esta página.')
            return redirect(url_for('index.Index'))
        
        return f(*args, **kwargs)
    
    return decorated_function

bp = Blueprint('index', __name__)

@bp.route('/', methods=['GET'])
def Index():
    try:
        user = session['user']
        
        if user['permisos'] == 2:
            return render_template('index/index_admin.html', bombero=user)
        
        elif user['permisos'] == 1:
            return render_template('index/index_user.html', bombero=user)
        
    except KeyError:
        return render_template('index/index_login.html')

@bp.route('/login', methods=['POST'])
def Login():
    username = request.form['username']
    password = request.form['password']
    
    bombero = Bombero.Get_Bombero_By_Username(username)
    
    if not bombero:
        bombero = Bombero.Get_Bombero_By_Legajo(username)
    
    if not bombero:
        bombero = Bombero.Get_Bombero_By_DNI(username)
    
    if bombero:
        if bombero.password == password:
            session['user'] = {
                'legajo': bombero.legajo,
                'username': bombero.username,
                'apellido_nombre': bombero.apellido_nombre,
                'permisos': bombero.permisos,
            }
            session['tema'] = 'color' # Tema por defecto
            session.permanent = True # Mantener la sesión activa
            
            return redirect(url_for('index.Index'))
        
        else:
            flash('Contraseña inválida')
            return redirect(url_for('index.Index'))
        
    else:
        flash('Usuario, legajo o DNI no encontrado')
        return redirect(url_for('index.Index'))

@bp.route('/logout', methods=['POST'])
def Logout():
    session.clear()
    return redirect(url_for('index.Index'))

@bp.route('/tema', methods=['POST'])
def Tema():
    tema_actual = session.get('tema', 'color')
    
    if tema_actual == 'color':
        session['tema'] = 'bw'
        
    else:
        session['tema'] = 'color'
    
    return redirect(request.referrer or url_for('index.Index'))

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Bomberos / {{ session['user']['username'] }}
    </title>

    <link rel="icon" href="{{ url_for('static', filename='logo.svg') }}" type="image/svg+xml">
    
    {% if session['tema'] == 'color' %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-color.css') }}">
    {% elif session['tema'] == 'bw' %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-bw.css') }}">
    {% else %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-color.css') }}">
    {% endif %}
    
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">

    {% block head %}
    {% endblock %}
</head>

<body>
    <div id="top">
        <h1><a href="{{ url_for('index.Index') }}">Bomberos Voluntarios de Totoras</a></h1>

        <div>
            <form action="{{ url_for('index.Tema') }}" method="post">
                <input type="submit" value="🖼️">
            </form>
    
            <form action="{{ url_for('index.Logout') }}" method="post">
                <input type="submit" value="❌">
            </form>
        </div>
    </div>

    <div id="middle">
        <div id="left">
            <div id="nav">
                <details open>
                    <summary>📑 Asistencias</summary>
                    <a href="{{ url_for('asistencias.Index') }}">📝 Cargar Planilla</a>
                    <a href="{{ url_for('asistencias.Verificar_Planillas') }}">📑 Verificar Planillas</a>
                    <a href="{{ url_for('asistencias.Ver_Planillas') }}">📄 Ver Planillas</a>
                </details>

                <details open>
                    <summary>🗃️ Calificaciones</summary>
                    <a href="{{ url_for('calificaciones.Mensual') }}">📅 Mensual</a>
                    <a href="{{ url_for('calificaciones.Semestral') }}">📆 Semestral</a>
                    <a href="{{ url_for('calificaciones.Anual') }}">🗓️ Anual</a>
                    <a href="{{ url_for('calificaciones.Historico') }}">🗂️ Histórico</a>
                </details>
    
                <details open>
                    <summary>📚 Datos</summary>
                    <a href="{{ url_for('personal.Personal') }}">📗 Personal</a>
                    <a href="{{ url_for('unidades.Unidades') }}">📕 Unidades</a>
                    <a href="{{ url_for('eventos.Eventos') }}">📘 Eventos</a>
                </details>
            </div>
    
            {% block left %}{% endblock %}
        </div>
    
        <div id="center">
            {% block center %}{% endblock %}
        </div>
    
        <div id="right">
            {% block right %}{% endblock %}

            {% with mensajes = get_flashed_messages()  %}
                {% if mensajes %}                
                    <fieldset class="flashes">
                        <legend>Mensajes</legend>

                        {% for mensaje in mensajes %}
                            <span>{{ mensaje }}</span>
                        {% endfor %}
                    </fieldset>
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <div id="bottom">
        <h2>IES №48, Martín Menna Castells © 2025</h2>
    </div>
</body>
</html>

flaskr/templates/base_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Bomberos / {{ session['user']['username'] }}
    </title>

    <link rel="icon" href="{{ url_for('static', filename='logo.svg') }}" type="image/svg+xml">

    {% if session['tema'] == 'color' %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-color.css') }}">
    {% elif session['tema'] == 'bw' %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-bw.css') }}">
    {% else %}
        <link rel="stylesheet" href="{{ url_for('static', filename='tema-color.css') }}">
    {% endif %}
    
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">

    {% block head %}
    {% endblock %}
</head>

<body>
    <div id="top">
        <h1><a href="{{ url_for('index.Index') }}">Bomberos Voluntarios de Totoras</a></h1>

        <form action="{{ url_for('index.Logout') }}" method="post">
            <input type="submit" value="❌">
        </form>
    </div>

    <div id="middle">
        <div id="left">
            <div id="nav">
                <details open>
                    <summary>📑 Asistencias</summary>
                    <a href="{{ url_for('asistencias.Index') }}">📝 Cargar Planilla</a>
                    <a href="{{ url_for('asistencias.Ver_Planillas') }}">📄 Ver Planillas</a>
                </details>

                <details open>
                    <summary>🗃️ Calificaciones</summary>
                    <a href="{{ url_for('calificaciones.Mensual') }}">📅 Mensual</a>
                    <a href="{{ url_for('calificaciones.Semestral') }}">📆 Semestral</a>
                    <a href="{{ url_for('calificaciones.Anual') }}">🗓️ Anual</a>
                    <a href="{{ url_for('calificaciones.Historico') }}">🗂️ Histórico</a>
                </details>
            </div>
    
            {% block left %}{% endblock %}
        </div>
    
        <div id="center">
            {% block center %}{% endblock %}
        </div>
    
        <div id="right">
            {% block right %}{% endblock %}

            {% with mensajes = get_flashed_messages()  %}
                {% if mensajes %}                
                    <fieldset class="flashes">
                        <legend>Mensajes</legend>

                        {% for mensaje in mensajes %}
                            <span>{{ mensaje }}</span>
                        {% endfor %}
                    </fieldset>
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <div id="bottom">
        <h2>IES №48, Martín Menna Castells © 2025</h2>
    </div>
</body>
</html>